language: python

python:
  - 3.4
  - 3.5

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database vk_activity_test;' -U postgres

script:
  - python init_db.py
